from PyQt5 import QtCore, QtGui, QtWidgets
import Calendar

class Ui_MainWindow(object):
    def setupUi_Main(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(900, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setBaseSize(QtCore.QSize(800, 600))
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setAutoFillBackground(True)
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget_1 = QtWidgets.QTableWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_1.sizePolicy().hasHeightForWidth())
        self.tableWidget_1.setSizePolicy(sizePolicy)
        self.tableWidget_1.setTabletTracking(False)
        self.tableWidget_1.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tableWidget_1.setLineWidth(1)
        self.tableWidget_1.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_1.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_1.setDragEnabled(False)
        self.tableWidget_1.setColumnCount(6)
        self.tableWidget_1.setObjectName("tableWidget_1")
        self.tableWidget_1.setRowCount(0)
        # self.tableWidget_1.horizontalHeader().setVisible(False)
        self.tableWidget_1.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_1.horizontalHeader().setDefaultSectionSize(128)
        self.tableWidget_1.horizontalHeader().setHighlightSections(True)
        self.tableWidget_1.horizontalHeader().setMinimumSectionSize(40)
        self.tableWidget_1.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_1.verticalHeader().setVisible(False)
        self.tableWidget_1.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget_1.verticalHeader().setHighlightSections(True)
        self.tableWidget_1.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout_2.addWidget(self.tableWidget_1)
        self.Refresh = QtWidgets.QPushButton(self.tab)
        self.Refresh.setObjectName("Refresh")
        self.verticalLayout_2.addWidget(self.Refresh)
        self.AddLine = QtWidgets.QPushButton(self.tab)
        self.AddLine.setObjectName("AddLine")
        self.verticalLayout_2.addWidget(self.AddLine)
        self.ChangeLine = QtWidgets.QPushButton(self.tab)
        self.ChangeLine.setObjectName("ChangeLine")
        self.verticalLayout_2.addWidget(self.ChangeLine)
        self.RemoveLine = QtWidgets.QPushButton(self.tab)
        self.RemoveLine.setObjectName("RemoveLine")
        self.verticalLayout_2.addWidget(self.RemoveLine)
        self.Exit = QtWidgets.QPushButton(self.tab)
        self.Exit.setObjectName("Exit")
        self.verticalLayout_2.addWidget(self.Exit)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_2.sizePolicy().hasHeightForWidth())
        self.tab_2.setSizePolicy(sizePolicy)
        self.tab_2.setAutoFillBackground(True)
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Calendar = Calendar.MyCalendar(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Calendar.sizePolicy().hasHeightForWidth())
        self.Calendar.setSizePolicy(sizePolicy)
        self.Calendar.setMinimumSize(QtCore.QSize(400, 0))
        self.Calendar.setGridVisible(True)
        self.Calendar.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.Calendar.setNavigationBarVisible(True)
        self.Calendar.setObjectName("Calendar")
        self.horizontalLayout.addWidget(self.Calendar)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_2.sizePolicy().hasHeightForWidth())
        self.tableWidget_2.setSizePolicy(sizePolicy)
        self.tableWidget_2.setTabletTracking(False)
        self.tableWidget_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tableWidget_2.setLineWidth(1)
        self.tableWidget_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_2.setDragEnabled(False)
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setRowCount(0)
        # self.tableWidget_2.horizontalHeader().setVisible(False)
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(128)
        self.tableWidget_2.horizontalHeader().setHighlightSections(False)
        self.tableWidget_2.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.tableWidget_2.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget_2.verticalHeader().setHighlightSections(True)
        self.tableWidget_2.verticalHeader().setSortIndicatorShown(False)
        self.horizontalLayout.addWidget(self.tableWidget_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        # Устанавливаем фиксированый размер для колонок

        self.tableWidget_1.setHorizontalHeaderLabels(["Id", "Заказчик", "Дата поставки", "Оплата", "Статус", "Email"])  # задаём названия колонок

        self.tableWidget_2.setHorizontalHeaderLabels(["Заказчик", "Дата поставки", "Оплата", "Статус"])  # задаём названия колонок

        self.tableWidget_1.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)  # !!!
        self.tableWidget_1.horizontalHeader().setDefaultSectionSize(40)
        self.tableWidget_1.horizontalHeader().setSectionResizeMode(0, QtWidgets.QHeaderView.Fixed)

        self.tableWidget_2.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)  # !!!

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Промышленное производство"))
        self.Refresh.setText(_translate("MainWindow", "Обновить"))
        self.AddLine.setText(_translate("MainWindow", "Добавить запись"))
        self.ChangeLine.setText(_translate("MainWindow", "Изменить запись"))
        self.RemoveLine.setText(_translate("MainWindow", "Удалить запись"))
        self.Exit.setText(_translate("MainWindow", "Выход"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Производство"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "График поставок"))

